# Generated by Django 6.0.3 on 2026-03-31 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_initial'),
        ('teachers', '0004_remove_teacher_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('grade_level', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to='teachers.teacher')),
                ('subjects', models.ManyToManyField(related_name='classes', to='subjects.subject')),
                ('teachers', models.ManyToManyField(related_name='teaching_classes', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['grade_level', 'name'],
            },
        ),
    ]
