# Generated by Django 6.0.3 on 2026-04-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubjectassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='classsubjectassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectassignment',
            unique_together={('school_class', 'subject')},
        ),
    ]
