# Generated by Django 6.0.3 on 2026-03-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0002_initial'),
        ('teachers', '0004_remove_teacher_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='section',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='teachers',
        ),
        migrations.CreateModel(
            name='ClassSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Class Subject Assignment',
                'verbose_name_plural': 'Class Subject Assignments',
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
