# Generated by Django 6.0.3 on 2026-03-31 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.schoolclass'),
        ),
    ]
