# Generated by Django 6.0.3 on 2026-03-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
    ]
