# Generated by Django 6.0.3 on 2026-03-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_department_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
