# Generated by Django 6.0.3 on 2026-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_remove_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
