# Generated by Django 6.0.3 on 2026-03-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
    ]
